export const GET_PRODUCTS = 'GET_PRODUCTS'
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS'
export const GET_PRODUCTS_FAILURE = 'GET_PRODUCTS_FAILURE'
export const SHOW_DETAILS_DIALOG = 'SHOW_DETAILS_DIALOG'
export const CLOSE_DIALOG = 'CLOSE_DIALOG'


export const ADD_TO_CART = "ADD_TO_CART"
export const UPDATE_CART_QUANTITY = 'UPDATE_CART_QUANTITY'
export const REMOVE_ITEM_CART = 'REMOVE_ITEM_CART'
export const SHOW_CONFIRMATION_DIALOG = 'SHOW_CONFIRMATION_DIALOG'
